# Generated by Django 5.1.1 on 2024-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
